version: "3"
services:
    duckdns:
      image: linuxserver/duckdns:503cba06-ls37
      container_name: duckdns
      environment:
        SUBDOMAINS: ${HOST}
        TOKEN: ${TOKEN}
        TZ: Europe/Paris
      restart: always
